<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="Castle.Core.AsyncInterceptor" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

</Project>
